package controllers;

import com.google.gson.Gson;
import entities.Message;
import org.apache.camel.util.Time;
import org.apache.flink.api.common.functions.AggregateFunction;
import org.apache.flink.api.common.serialization.SerializationSchema;
import org.apache.flink.api.common.serialization.SimpleStringSchema;
import org.apache.flink.streaming.api.datastream.DataStream;
import org.apache.flink.streaming.api.datastream.DataStreamSource;
import org.apache.flink.streaming.api.datastream.SingleOutputStreamOperator;
import org.apache.flink.streaming.api.environment.StreamExecutionEnvironment;
import org.apache.flink.streaming.connectors.kafka.FlinkKafkaConsumer011;
import org.apache.flink.streaming.connectors.kafka.FlinkKafkaProducer011;
import scala.Tuple2;

import java.util.Properties;

public class FlinkController {

    private static String INPUT_KAFKA_TOPIC = null;
    private static int TIME_WINDOW = 0;
    private static final String topicname = "monitorer";
    private static int count = 0;



    public void calculateAvg() throws Exception {

        INPUT_KAFKA_TOPIC = "semaphoresensor";
        TIME_WINDOW = 10;
        Properties properties = new Properties();
        properties.setProperty("bootstrap.servers", "localhost:9092");
        properties.setProperty("zookeeper.connect", "localhost:2181");
        properties.setProperty("group.id", INPUT_KAFKA_TOPIC);
        StreamExecutionEnvironment env = StreamExecutionEnvironment.getExecutionEnvironment();
        DataStreamSource<String> stream = env.addSource(new FlinkKafkaConsumer011(INPUT_KAFKA_TOPIC, new SimpleStringSchema(), properties));

        System.out.println("got sources");
        // DataStream<Tuple11<String, String, String, String, String, Int, Double, Double ,Boolean,Boolean,Boolean>> streamTuples = stream.flatMap(new SemaphoreJson2Tuple());
        DataStream<Tuple2<String, Double>> streamTuples = stream.flatMap(new SemaphoreJson2Tuple());

        streamTuples.print();
        SingleOutputStreamOperator<Double> averageSpeedStream = streamTuples
                .keyBy(new int[]{0})
                .timeWindow(Time.seconds((long)TIME_WINDOW))
                .aggregate((AggregateFunction<Tuple2<String, Double>, Tuple2<Double, Double>, Double>) new AverageAggregate());


        //write to another kafka topic
        averageSpeedStream.addSink(new FlinkKafkaProducer011<>("localhost:9092", topicname, (SerializationSchema<Tuple2<String, Double>>) stringDoubleTuple2 -> {
            Gson gson = new Gson();
            String key = stringDoubleTuple2.f0;
            double value = stringDoubleTuple2.f1;
            FlinkResult flinkResult = new FlinkResult(key, value, count);
            count = 0;

            Message m = new Message("flinkDispatcher", 701);
            m.setFlinkResult(flinkResult);
            String result = gson.toJson(m);
            return result.getBytes();
        }));

        averageSpeedStream.print();
        env.execute("Window Traffic Data");

    }





/*
    Following Class executes flink for tuples generated by semaphores' sensor.
 */

    private static class AverageAggregate implements AggregateFunction<Tuple2<String, Double>, Tuple2<Double, Double>, Double> {

        @Override
        public Tuple2<Double, Double> createAccumulator() {
            return new Tuple2<>(0.0, 0.0);
        }

        @Override
        public Tuple2<Double, Double> add(Tuple2<String, Double> value, Tuple2<Double, Double> accumulator) {
            return new Tuple2<>(accumulator.f0 + value.f1, accumulator.f1 + 1.0);
        }

        @Override
        public Double getResult(Tuple2<Double, Double> accumulator) {
            return accumulator.f0 / accumulator.f1;        }

        @Override
        public Tuple2<Double, Double> merge(Tuple2<Double, Double> a, Tuple2<Double, Double> b) {
            return new Tuple2<>(a.f0 + b.f0, a.f1 + b.f1);
        }
    }


    /*public static class SemaphoreJson2Tuple implements FlatMapFunction<String, Tuple2<String,Double>> {
        public SemaphoreJson2Tuple() {
        }

        @Override
        public void flatMap(String jsonString, Collector<Tuple2<String, Double>> out) throws Exception {
            ArrayList<SemaphoreSensor> recs = SemaphoreJsonReader.getSemaphoreDatas(jsonString);
            Iterator irecs = recs.iterator();

            while(irecs.hasNext()) {
                SemaphoreSensor record = (SemaphoreSensor) irecs.next();
                Tuple2 tp2 = new Tuple2();
                tp2.setField(record.getSemaphoreID(), 0);
                tp2.setField(record.getMeanSpeed(), 1 );

                out.collect(tp2);
            }

        }*/


}
